### ISSUE TITLE
How to add custom procedural Masks/Filters?

### ISSUE THREAD

**Issue by unfa** [joshuaKnauber/layer_painter#16]
I see that Layer Painter cleverly uses Node Groups for it's work.

I wonder how I could add custom Filter / Mask nodes to have more control over the procedural patterns used.

Is this documented anywhere? Is it supported without having to modify the add-ons code?

**Comment by joshuaKnauber** [comment]
You can do this by creating a node group and adding the file in the preferences. Just as a heads up, it would be better if you could use discord for these kinds of questions

**Comment by unfa** [comment]
Thanks!
